export const BOOK_GENRES = [
  'Fantasy',
  'Science Fiction',
  'Thriller',
  'Mystery',
  'Romance',
  'Historical Fiction',
  'Horror',
  'Adventure',
  'Young Adult',
  'Non-Fiction',
  'Biography',
  'Self-Help',
  'Poetry',
  'Drama',
  'Classic',
  'Dystopian',
  'Graphic Novel',
  'Crime',
  'Memoir',
  'Humor',
];
